import { Palette } from "std-widgets.slint";
import { SystemTheme } from "../types.slint";

export component FlatLineInput inherits Rectangle {
    in-out property <string> text;
    in property <bool> enabled: true;
    in property <string> input-label: "";
    in property <length> font-size: 14px;
    out property <bool> has-focus: input.has-focus;
    callback accepted;

    forward-focus: input;
    background: transparent;
    clip: true;

    input-clip := Rectangle {
        x: 10px;
        width: max(0px, parent.width - 20px);
        height: parent.height - 1px;
        clip: true;
        background: transparent;

        input := TextInput {
            private property <length> computed-x;

            x: min(0px, max(parent.width - self.width - self.text-cursor-width, self.computed-x));
            width: max(parent.width - self.text-cursor-width, self.preferred-width);
            height: parent.height;
            text <=> root.text;
            enabled: root.enabled;
            color: Palette.foreground;
            font-size: root.font-size;
            single-line: true;
            vertical-alignment: center;
            selection-background-color: SystemTheme.selection-background;
            selection-foreground-color: SystemTheme.selection-foreground;
            accessible-label: root.input-label;

            cursor-position-changed(position) => {
                if position.x + self.computed-x < 0px {
                    self.computed-x = -position.x;
                } else if position.x + self.computed-x > parent.width - self.text-cursor-width {
                    self.computed-x = parent.width - position.x - self.text-cursor-width;
                }
            }
            accepted => { root.accepted(); }
        }
    }

    Rectangle {
        y: parent.height - 1px;
        height: 1px;
        background: SystemTheme.accent;
    }
}
