import { ListView } from "std-widgets.slint";
import { FileItem } from "../types.slint";
import { RangerRow } from "ranger-row.slint";

export component RangerColumn inherits Rectangle {
    in property <[FileItem]> files;
    in property <int> selected-index: -1;
    in property <[bool]> selected-entries;
    in property <bool> use-extended-selection: false;
    in property <bool> actions-enabled;
    in property <bool> drag-enabled;
    in property <bool> drop-enabled;
    callback clicked(int);
    callback double-clicked(int);
    callback context-selected(int);
    callback rename-requested(int);
    callback trash-requested(int);
    pure callback drop-allowed(data-transfer, int) -> bool;
    callback dropped(data-transfer, int) -> bool;

    changed selected-index => {
        if root.selected-index < 0 {
            return;
        }
        let item-top = root.selected-index * 32px;
        let visible-top = -list.viewport-y;
        if item-top < visible-top {
            list.viewport-y = -item-top;
        } else if item-top + 32px > visible-top + list.visible-height {
            list.viewport-y = -(item-top + 32px - list.visible-height);
        }
    }

    list := ListView {
        for file[index] in root.files : RangerRow {
            width: parent.width;
            item: file;
            item-index: index;
            selected: root.use-extended-selection
                ? root.selected-entries[index]
                : root.selected-index == index;
            actions-enabled: root.actions-enabled;
            drag-enabled: root.drag-enabled;
            drop-enabled: root.drop-enabled;
            clicked(index) => { root.clicked(index); }
            double-clicked(index) => { root.double-clicked(index); }
            context-selected(index) => { root.context-selected(index); }
            rename-requested(index) => { root.rename-requested(index); }
            trash-requested(index) => { root.trash-requested(index); }
            drop-allowed(data, index) => { root.drop-allowed(data, index) }
            dropped(data, index) => { root.dropped(data, index) }
        }
    }
}
