import { Palette, LineEdit } from "std-widgets.slint";
import { SystemTheme } from "../types.slint";

export component ThemedLineInput inherits Rectangle {
    in-out property <string> text;
    in property <bool> enabled: true;
    in property <bool> single-line: true;
    in property <InputType> input-type: InputType.text;
    in property <string> input-label: "";
    in property <string> font-family: "";
    in property <bool> font-italic: false;
    in property <length> font-size: 0px;
    in property <int> font-weight: 400;
    in property <TextHorizontalAlignment> horizontal-alignment: TextHorizontalAlignment.left;
    in property <bool> read-only: false;

    out property <bool> has-focus;
    callback accepted;
    forward-focus: input;

    background: Palette.control-background;
    border-width: 1px;
    border-color: self.has-focus ? SystemTheme.accent : Palette.border;
    border-radius: 6px;
    clip: true;

    HorizontalLayout {
        x: 10px;
        y: 0px;
        height: 100%;

        input := LineEdit {
            text <=> root.text;
            enabled: root.enabled;
            input-type: root.input-type;
            horizontal-alignment: root.horizontal-alignment;
            read-only: root.read-only;
            font-family: root.font-family;
            font-italic: root.font-italic;
            font-size: root.font-size;
            accepted => { root.accepted(); }

            width: max(0px, parent.width);
            height: 100%;
            accessible-label: root.input-label;
        }
    }

    public function focus-input() {
        input.focus();
    }

    public function select-all() {
        input.select-all();
    }
}
